apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javatest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Annynetwork/java.git
    targetRevision: HEAD
    path: javatesting

  destination:
    server: https://kubernetes.default.svc
    namespace: javatesting

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
 
    automated:
      selfHeal: true
      prune: false
