apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-demo1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Annynetwork/java.git
    targetRevision: HEAD
    path: spring       
  
  destination:
    server: https://kubernetes.default.svc
    namespace: demo1
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
   
    automated:
      selfHeal: true
      prune: false
