---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8443
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:17.0.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        #ENV KC_HOSTNAME=localhost:8443
        ports:
        - name: http
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8443
        volumeMounts:
        - name: keycloak
          mountPath: "/etc/ssl/certs/"
          readOnly: true
      volumes:
      - name: keycloak
        secret:
          secretName: localdomain
