---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8443
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:17.0.1
        args: ["start-dev"]
        volumeMounts:
        - name: keycloak
          mountPath: "/etc/ssl/certs/"
          readOnly: true
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: keycloak
          value:
            secret:
              secretName: localdomain
        ports:
        - name: http
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8443
      
 
        #- secretName: example-com-tls1
          #value: "keycloak_tls.crt"
          #configMap:
          #name: keycloak
          #ADD /mnt/d/All/java/tomcat/spring-maven-sample/keycloak_tls.crt /etc/ssl/certs/keycloak_tls.crt
#RUN chmod 644 /etc/ssl/certs/keycloak_tls.crt
#RUN update-ca-certificates
