apiVersion:v1
kind:ReplicationController
 metadata:
            name: appname
            spec:
                     replicas:replica_count
                      template: 
                         metadata:
                                     name: appname
                                         labels:
                                                       k8s-app:   appname
                                                             component:nginx
                                                                   env:env_name
                                                       spec:
                                                                 nodeSelector:
                                                                            resource-group: dev
                                                                             containers:
                                                                                       - name: appname 
                                                                                           image:IMAGE_TEMPLATE 
                                                                                             imagePullPolicy:Always 
                                                                                               ports: 
                                                                                                  -containerPort: 8080
                                                                                                     resources:
                                                                                                                 requests:
                                                                                                                              memory: "request_mem"
                                                                                                                                   cpu: "request_cpu" 
                                                                                                                                       limits:
                                                                                                                                                     memory: "limit_mem"
                                                                                                                                                           cpu: "limit_cpu" 
                                                                                                                                                               env: - name: BACKEND_HOST
                                                                                                                                                                   value: dev-env_name-node:3000

