apiVersion: v1
kind: Service
metadata: 
 name: backend
   labels:
               k8s-app: backend
               spec:
                        type: NodePort
                         ports
                          - name:http
                               port: 9010
                                  protocol:TCP
                                     targetPort: 9000
                                      selector:
                                                k8s-app: appname
                                                  component: play
                                                    env: dev
