apiVersion:v1
kind:ReplicationController
 metadata:
            name: Frontend
            spec:
                     replicas:3
                      template: 
                         metadata:
                                     name: Frontend
                                         labels:
                                                       k8s-app: Frontend
                                                             component:java
                                                                   env:dev
                                                       spec:
                                                                 nodeSelector:
                                                                            resource-group: dev
                                                                             containers:
                                                                                       - name: appname 
                                                                                           image:IMAGE_TEMPLATE 
                                                                                             imagePullPolicy:Always 
                                                                                               ports: 
                                                                                                  -containerPort:3000
                                                                                                     resources:
                                                                                                                 requests:
                                                                                                                              memory: "request_mem"
                                                                                                                                   cpu: "request_cpu" 
                                                                                                                                       limits:
                                                                                                                                                     memory: "limit_mem"
                                                                                                                                                           cpu: "limit_cpu" 
                                                                                                                                                               env:
                                                                                                                                                                            -name: ENV
                                                                                                                                                                                 valueFrom:
                                                                                                                                                                                              configMapKeyRef:
                                                                                                                                                                                                           name:appname
                                                                                                                                                                                                                Key:congfig-env
