apiVersion: v1
kind: Service
metadata: 
 name: appname
   labels:
               k8s-app: appname
               spec:
                        type: NodePort
                         ports
                          - name:http
                               port: 3000
                                  protocol:TCP
                                     targetPort: 3000
                                      selector:
                                                k8s-app: appname
                                                  component: java
                                                    env: dev
