apiVersion: v1
kind: Service
metadata: 
 name: dev-nginx
   labels:
               k8s-app: dev-api
               spec:
                        type: NodePort
                         ports:
                                  - port: 8080
                                        nodePort: 31900 name: devnginx
                                         selector:
                                                   k8s-app: appname
                                                     component: nginx
                                                       env: dev
